/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_SERVICE_H_RPCGEN
#define _RPC_SERVICE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct operation_1_argument {
	char *arg1;
	char *arg2;
	char *arg3;
	char *arg4;
};
typedef struct operation_1_argument operation_1_argument;

#define SERVER 0x31230000
#define SERVER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define OPERATION 1
extern  enum clnt_stat operation_1(char *, char *, char *, char *, int *, CLIENT *);
extern  bool_t operation_1_svc(char *, char *, char *, char *, int *, struct svc_req *);
extern int server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OPERATION 1
extern  enum clnt_stat operation_1();
extern  bool_t operation_1_svc();
extern int server_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operation_1_argument (XDR *, operation_1_argument*);

#else /* K&R C */
extern bool_t xdr_operation_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_SERVICE_H_RPCGEN */
