/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_service.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_register_1 (register_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (register_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_unregister_1 (unregister_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (unregister_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_connect_1 (connect_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (connect_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_disconnect_1 (disconnect_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (disconnect_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_publish_1 (publish_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (publish_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, result, rqstp));
}

int
_delete_1 (delete_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (delete_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, result, rqstp));
}

int
_list_users_1 (list_users_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (list_users_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

int
_list_content_1 (list_content_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (list_content_1_svc(argp->arg1, argp->arg2, argp->arg3, result, rqstp));
}

static void
server_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		register_1_argument register_1_arg;
		unregister_1_argument unregister_1_arg;
		connect_1_argument connect_1_arg;
		disconnect_1_argument disconnect_1_arg;
		publish_1_argument publish_1_arg;
		delete_1_argument delete_1_arg;
		list_users_1_argument list_users_1_arg;
		list_content_1_argument list_content_1_arg;
	} argument;
	union {
		int register_1_res;
		int unregister_1_res;
		int connect_1_res;
		int disconnect_1_res;
		int publish_1_res;
		int delete_1_res;
		int list_users_1_res;
		int list_content_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REGISTER:
		_xdr_argument = (xdrproc_t) xdr_register_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_register_1;
		break;

	case UNREGISTER:
		_xdr_argument = (xdrproc_t) xdr_unregister_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_unregister_1;
		break;

	case CONNECT:
		_xdr_argument = (xdrproc_t) xdr_connect_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_connect_1;
		break;

	case DISCONNECT:
		_xdr_argument = (xdrproc_t) xdr_disconnect_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_disconnect_1;
		break;

	case PUBLISH:
		_xdr_argument = (xdrproc_t) xdr_publish_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_publish_1;
		break;

	case DELETE:
		_xdr_argument = (xdrproc_t) xdr_delete_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_delete_1;
		break;

	case LIST_USERS:
		_xdr_argument = (xdrproc_t) xdr_list_users_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_list_users_1;
		break;

	case LIST_CONTENT:
		_xdr_argument = (xdrproc_t) xdr_list_content_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_list_content_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!server_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SERVER, SERVER_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SERVER, SERVER_VERS, server_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SERVER, SERVER_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SERVER, SERVER_VERS, server_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SERVER, SERVER_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
